name: Vite Build and Deploy to GCP VM

on:
  push:
    branches:
      - main  
    paths-ignore:
      - 'README.md'
    if: contains(github.event.head_commit.message, 'deploy')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefix veganOfficialWeb

      - name: Build Vite project
        run: npm run build --prefix veganOfficialWeb

      - name: Deploy to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: /veganOfficialWeb/dist/
          target: "/home/thomas_c/tmp/uploads/dist"
          proxy_host: ${{ secrets.PROXY_IP }}
