name: Vite Build and Deploy to GCP VM

on:
  push:
    branches:
      - main  
    paths-ignore:
      - 'README.md'
    if: contains(github.event.head_commit.message, 'deploy')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH connection
        run: |
          ping -c 4 ${{ secrets.VM_HOST }}
          nc -zv ${{ secrets.VM_HOST }} 22
          ssh -vvv ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} -o StrictHostKeyChecking=no echo "Connection test"
    
