name: Deploy to GCE via IAP SSH

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: |
      github.event.pull_request.merged == true &&
      (
        contains(github.event.pull_request.title, 'deploy') ||
        contains(github.event.pull_request.title, 'release') ||
        contains(github.event.pull_request.body, 'deploy') ||
        contains(github.event.pull_request.body, 'release')
      )
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Build vue
        run: |
          cd veganOfficialWeb
          npm ci
          npm run build-only
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_ADMIN_ACCOUNT: ${{ secrets.VITE_ADMIN_ACCOUNT }}
          VITE_ADMIN_PASSWORD: ${{ secrets.VITE_ADMIN_PASSWORD }}

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: SCP Transfer vue File via IAP
        run: |
          gcloud compute ssh ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }} \
            --zone=${{ secrets.GCE_ZONE }} \
            --tunnel-through-iap \
            --command "sudo rm -rf ~/tmp/uploads/dist && mkdir -p ~/tmp/uploads/dist"

          gcloud compute scp --recurse veganOfficialWeb/dist/* ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }}:~/tmp/uploads/dist \
              --zone=${{ secrets.GCE_ZONE }} \
              --tunnel-through-iap \
              || exit 1

      - name: SSH Connection via IAP
        run: |
          gcloud compute ssh ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }} \
              --zone=${{ secrets.GCE_ZONE }} \
              --tunnel-through-iap \
              --command "
              cd ~/app/sp01_VeganWebsite/veganWebServer &&  
              git pull origin main &&        
              npm install &&
              sudo rm -rf /var/www/html/dist/* &&
              sudo cp -r ~/tmp/uploads/dist/* /var/www/html/dist/ &&
              pm2 restart all
              "
          echo "Deployment completed"