name: Deploy to GCE via IAP SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'deploy') || 
      contains(github.event.head_commit.message, 'release')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Build vue
        run: |
          cd veganOfficialWeb
          npm ci
          npm run build-only

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: SCP Transfer vue File via IAP
        run: |
          gcloud compute scp --recurse veganOfficialWeb/dist ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }}:~/tmp/uploads/dist \
              --zone=${{ secrets.GCE_ZONE }} \
              --tunnel-through-iap \
              || exit 1

      - name: SSH Connection via IAP
        run: |
          gcloud compute ssh ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }} \
              --zone=${{ secrets.GCE_ZONE }} \
              --tunnel-through-iap \
              --command "
              cd ~/app/sp01_VeganWebsite/veganWebServer &&  
              git pull origin main &&        
              npm install &&
              sudo cp -r ~/tmp/uploads/dist/* /var/www/html/dist &&
              pm2 restart all
              "
              
      - name: Health Check
        run: |
          max_retries=5
          counter=0
          until curl -v -f https://${{ secrets.APP_DOMAIN }} 2>&1 || [ $counter -eq $max_retries ]
          do
            echo "嘗試次數 $((counter + 1)) / $max_retries"
            echo "等待 10 秒後重試..."
            curl -v https://${{ secrets.APP_DOMAIN }} 2>&1
            sleep 10
            counter=$((counter + 1))
          done
          
          if [ $counter -eq $max_retries ]; then
            exit 1
          fi
          
          echo "服務正常運作中！"
